### ISSUE TITLE
Update only specific job data

### ISSUE THREAD

**Issue by ujovlado** [keboola/syrup#102]
Related to: https://github.com/keboola/syrup/pull/101

Bolo by fajn, keby job mapper vedel updatnut len niektore data (t.j. len potrebne) a nie vsetky. Moze to sposovbovat problemy ako v issue vyssie.

**Comment by ujovlado** [comment]
Idealne by bolo mat tam nejaky `JobCrate` objekt, ktory by vedel drzat len tu cast dat, ktora sa ma updatnut.

**Comment by odinuv** [comment]
obsolete
