### ISSUE TITLE
Run Job - S3 attachment

### ISSUE THREAD

**Issue by Halama** [keboola/syrup#105]
Spuštění jobu imho zbytečně loguje do S3 a tím zpomaluje odezvu API callu.
![image](https://cloud.githubusercontent.com/assets/903531/23942563/f9477c16-096c-11e7-8ae5-0ef17c8b9d2c.png)

![image](https://cloud.githubusercontent.com/assets/903531/23942592/14105d9c-096d-11e7-86d6-15a7dcf3c531.png)

**Comment by MiroCillik** [comment]
Vypada, ze to zabera naozaj dost casu, mozme to vyhodit. Respektive vyhodit ten s3 "attachment".

**Comment by odinuv** [comment]
obsolete
