### ISSUE TITLE
Missing encryption tests

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/syrup#106]
Doplnit test, který otestuje, že se objekty neencryptují, tj

```
{"#key": {"key2": "value"}}
```

https://github.com/keboola/syrup/blob/720e8f457d322307e6a893d87d97acd4b41f0cc6/src/Keboola/Syrup/Service/ObjectEncryptor.php#L233

**Comment by odinuv** [comment]
part of https://github.com/keboola/object-encryptor/blob/master/tests/ObjectEncryptorTest.php#L463
