### ISSUE TITLE
Elasticsearch\Common\Exceptions\Serializer\JsonSerialization: Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/syrup#112]
https://connection.keboola.com/admin/utils/logs?file=2017/10/15/07/2017-10-15-07-54-47-59e2f82722100-exception
https://connection.keboola.com/admin/utils/logs?file=2017/10/15/07/2017-10-15-07-54-47-59e2f82741d6f-log

před serializací do JSONu by se result message měla sanitizovat

**Comment by odinuv** [comment]
stejne si myslim, ze by to mel resit docker runner. DR je interface pro cizi komponenty, tak ma resit aby z cizi komponenty nelezl bordel. cili rekl bych - nase komponenty jsou utf-8 takze neco, co potencionalne neni utf8 musime do utf8 prevest asap

**Comment by ondrejhlavacek** [comment]
Dobrá! Vrhnu se na to ASAP.
