### ISSUE TITLE
Invalid token in job

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/syrup#117]
1) Vytvořit token
2) Založit s tokenem job
3) Smazat token
4) Spustí se job a vyfailuje bez jediné hlášky a prudí nás s 500

Asi to nemá pro uživatele nějaký rozumný řešení, ale aspoň by nás to nemuselo prudit s 500? :-)

Detail vyfailovaného jobu

![image](https://user-images.githubusercontent.com/497675/35614135-5a66ae3c-066e-11e8-8227-3c3d543586b7.png)

![image](https://user-images.githubusercontent.com/497675/35614151-632d1bfa-066e-11e8-8061-7b10e2b5e7c8.png)

Detail z PT

![image](https://user-images.githubusercontent.com/497675/35614165-6cafb78c-066e-11e8-9ed9-7f2b46ad6299.png)

Stack Tracy

https://connection.keboola.com/admin/utils/logs?file=2018/01/31/10/2018-01-31-10-04-00-5a718680c270b-exception
https://connection.keboola.com/admin/utils/logs?file=2018/01/31/10/2018-01-31-10-04-00-5a718680c8295-log

**Comment by odinuv** [comment]
obsolete
