### ISSUE TITLE
run config rows with invalid input should be user error

### ISSUE THREAD

**Issue by kacurez** [keboola/syrup#133]
copied from https://github.com/keboola/docker-bundle/issues/394
https://keboola.slack.com/archives/C02CGK5CL/p1549639567042800

run body: `{"config":"358642681","row":{"id":"463615221"},"component":"keboola.ex-aws-s3","mode":"run"}`

result:
`
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse [params.row]"}],"type":"mapper_parsing_exception","reason":"failed to parse [params.row]","caused_by":{"type":"illegal_argument_exception","reason":"unknown property [id]"}},"status":400}
`

**Comment by odinuv** [comment]
toto je afaik vyřešený validací v runneru
