### ISSUE TITLE
Add option to log to stdout

### ISSUE THREAD

**Issue by ujovlado** [keboola/syrup#134]
Pripravujeme presun na beh v kontajneroch. Jednou z dolezitych casti je aby sa logovalo na stdout.

Momentalne mame odladeny setup tak, ze nam bezi logspout kontajner, ktory zbiera logy s "okolitych" kotajnerov z ich stdout a posiela ich do PT.

Syrup na niektorcyh miestach pouziva rovno syslog, co prestane fungovat, pretoze ziadny syslog tam bezat nebude.

**Comment by ujovlado** [comment]
https://github.com/keboola/syrup/search?q=syslog&unscoped_q=syslog

**Comment by ujovlado** [comment]
Najdolezitejsie je zbavit sa toho tu:

https://github.com/keboola/syrup/blob/8708a92a131b68014e60c93d053e976e520dec0d/src/Keboola/Syrup/Debug/ExceptionHandler.php#L85-L88

Aby sme tie chyby mali spravne zalogovane.

**Comment by ujovlado** [comment]
^ Teda nie zbavit ale mat moznost to prepnut na stdout.

**Comment by odinuv** [comment]
to by melo jit uplne doprdele, zadny prepinani. nejelpsi by bylo vydat novou major verzi syrupu, ktera bude urcena jen pro zdrockerovany appky?

**Comment by ujovlado** [comment]
Asi jo, este som sa v tom nevrtal do detailu. Zalozil som to takto "opatrne" preto, lebo neviem ako narocne je, aby vsetky apky isli na najnovsom syrupe. Teraz je to tak, ze jedna ide na 5, dalsia na 6 napr.

**Comment by ujovlado** [comment]
Ale asi to spravim ako pises, vyhodim to. :)

**Comment by odinuv** [comment]
hmm, no koukam:
- provisiioning-bundle na 5
- orchestrator bundle na 7
- docker runnet a transformation na 10

ale ta aktualizace se bude muset nejspis udelat tak jako tak

**Comment by ujovlado** [comment]
a queue zase 6 :)

**Comment by ujovlado** [comment]
skoda, ze nie je tych komponent viac, mozno by sme obsiahli vsetky major verzie :)

**Comment by odinuv** [comment]
mam se treba podivat na ten provisioning nebo to stihas?

**Comment by ujovlado** [comment]
mas na mysli ten update syrupu?

**Comment by odinuv** [comment]
j
