### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by yustme** [keboola/syrup#135]
Během dotazu na
```
SELECT access_key, secret_key, region, url FROM queues WHERE id = 'tapi''
```
se stalo `SQLSTATE[HY000] [2002] Connection timed out`.

Nevím jestli to je přímo bug, ale asi by tam měla být nějaký retry. V projektu teda nic neselhalo, takže nevím jestli to bug.

**Comment by odinuv** [comment]
neopakuje se
