### ISSUE TITLE
VPC elastic 503

### ISSUE THREAD

**Issue by Halama** [keboola/syrup#137]
Nedostupný elastic způsobil pád několika orchestračních jobů.

Status: http://status.keboola.com/some-orchestration-failures-in-the-us-region

## Chyba
Syrup házel v moment kdy se rolovaly nody clusteru asi minutu `503 Service Temporarily Unavailable` https://papertrailapp.com/groups/23635/events?q=Elastic%20server%20error%20response%20 .  Způsobilo to pád asi 40 orchestračních jobů.
Vypadá to že všechny chyby šly z orchestrátoru:
```
Trace
in GuzzleConnection.php line 247
at GuzzleConnection->process5xxError(object(Request), object(ServerErrorResponseException), null) in GuzzleConnection.php line 200
at GuzzleConnection->sendRequest(object(Request), null) in GuzzleConnection.php line 104
at GuzzleConnection->performRequest('GET', '/_alias/prod_syrup_orchestrator', array(), null) in Transport.php line 166
at Transport->performRequest('GET', '/_alias/prod_syrup_orchestrator', array(), null) in AbstractEndpoint.php line 86
at AbstractEndpoint->performRequest() in IndicesNamespace.php line 755
at IndicesNamespace->getAlias(array('name' => 'prod_syrup_orchestrator')) in ComponentIndex.php line 103
at ComponentIndex->getIndices() in JobMapper.php line 156
at JobMapper->get('496193794') in JobCommand.php line 285
at JobCommand->execute(object(ArgvInput), object(ConsoleOutput)) in Command.php line 239
at Command->run(object(ArgvInput), object(ConsoleOutput)) in Application.php line 849
at Application->doRunCommand(object(JobCommand), object(ArgvInput), object(ConsoleOutput)) in Application.php line 190
at Application->doRun(object(ArgvInput), object(ConsoleOutput)) in Application.php line 81
at Application->doRun(object(ArgvInput), object(ConsoleOutput)) in Application.php line 114
at Application->run(object(ArgvInput)) in console line 23
```

https://connection.keboola.com/admin/utils/logs?file=2019/04/13/14/2019-04-13-14-16-39-5cb1ef4766554-exception

## Příčina?
Syrup máme připojený na AWS Elastic ve [VPC](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-vpc.html). V tomto režimu není pod jeho hostname load balancer ale vrací přímo privatní IP nodů. V moment kdy se cluster roluje (update services software, změna typu instancí, atd.) se IPs mění.

> Because the IP addresses might change, you should resolve the domain endpoint periodically so that you can always access the correct data nodes. We recommend that you set the DNS resolution interval to one minute. If you’re using a client, you should also ensure that the DNS cache in the client is cleared.

```
dig vpc-kbc-syrup-elasticsearch-3-7jyfsoeglcvuw5bda3hmsu4zfi.us-east-1.es.amazonaws.com

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.68.rc1.59.amzn1 <<>> vpc-kbc-syrup-xxx.us-east-1.es.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63970
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;vpc-kbc-syrup-xxx.us-east-1.es.amazonaws.com. IN	A

;; ANSWER SECTION:
vpc-kbc-syrup-xxx.us-east-1.es.amazonaws.com. 55	IN A 10.0.70.149
vpc-kbc-syrup-xxx.us-east-1.es.amazonaws.com. 55	IN A 10.0.71.11

;; Query time: 0 msec
;; SERVER: 10.0.0.2#53(10.0.0.2)
;; WHEN: Sat Apr 13 15:06:30 2019
;; MSG SIZE  rcvd: 133
```

Myslím si že se to dotazovalo staré IP pod kterou už elastic byl odpojený.
Na Elastic query v daném místě máme sice retry https://github.com/keboola/syrup/blob/aed8243fd403280a8b6391a2f0d5a841e4e3461c/src/Keboola/Syrup/Elasticsearch/ComponentIndex.php#L116 ale je nastavené jenom na 5 pokus  s malým odstupem, maximálně čeká cca. 32 sec. V logu je vidět že počet retries se vyčerpal a pak to tedy skončilo internal errorem.

## Oprava
Bude stačit na fix zvednout čas retry přes minutu? Bude potřeba vyzkoušet nad clusterem který zrovna mění IP nodů. 

Dokud to nefixneme hrozí že se to bude opakovat při každém updatu které AWS poslední dobou publikuje skoro každý měsíc https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/release-notes.html#release-table

**Comment by Halama** [comment]
Při update Syrup EU to teď ale neudělalo https://github.com/keboola/internal/issues/172#issuecomment-482940198

**Comment by Halama** [comment]
Rychle jsem to zkoušel na testingu a tam se mi to při rolování clusteru nepodařilo nasimulovat `ab  -n 5000000 https://vpc-syrup-testing-elastic-puqxh47an3ynkm7csnjmfyaxd4.us-east-1.es.amazonaws.com/`.
Možná to teda bude něčím jiným, mohli bysme zkusit support.

**Comment by Halama** [comment]
Bude potřeba se podívat jestli se to skutečně dělo jenom na tom orchestrátoru. Např. bych ověřil jestli syrup API neházelo 500. Potom bych mrknul do metrik toho elasticu jestli to ty 503 zaevidovalo.

**Comment by Halama** [comment]
Nejsem si jistý jestli tje to tím ale asi nejjednodušší bude zvednout tu dobu retry aby to bylo přes minutu. Je teda divný že to dělalo asi jenom pro ten dotaz orchestrátoru na 
```
Server error response
[status code] 503
[reason phrase] Service Temporarily Unavailable
[url] https://vpc-kbc-syrup-elasticsearch-3-7jyfsoeglcvuw5bda3hmsu4zfi.us-east-1.es.amazonaws.com/_alias/prod_syrup_orchestrator
```

**Comment by Halama** [comment]
Koukám že ta implementace tech retries je tam na X místech tak pokud se to bude zvedat tak by to asi chtělo všude https://github.com/keboola/syrup/search?q=%22Elastic+server+error+response%22&unscoped_q=%22Elastic+server+error+response%22

**Comment by Halama** [comment]
Moc jsem se ze supportu nedozvěděl ale řekli alespon že za tím je ALB a že chvíli označit dva uzly jako vadné to mohlo házet tu 503 než to odpojily.  A timeout ALB je 60 sec, takže to zvýšení toho retry by mohlo pomoct.
https://github.com/keboola/devops/issues/7#issuecomment-487846460

**Comment by Halama** [comment]
Stalo se to znovu, když se dívám do tech logů https://papertrailapp.com/groups/170211/events?q=(%27%22priority%22%3A%22CRITICAL%22%27%20OR%20%27%22priority%22%3A%22ALERT%22%27)%20-%27%22app%22%3A%22docker%22%27%20-%27%22component%22%3A%22ex-facebook%22%27%20-%22Storage%20backend%20migration%22%20-%27%22component%22%3A%22restbox%22%27%20-%22MaintenanceException%22 
Přijde mi že to neloguje ty retries. Zajímalo by mě tedy jestli je to vůbec dělá a proč nejsou zalogovaný pokud ano.

**Comment by Halama** [comment]
Do componentIndex ve kterém to hodilo chybu to logger předává https://github.com/keboola/syrup/blob/7.2.1/app/config/services.yml#L84

**Comment by Halama** [comment]
Ne tak to retry loguje i funguje vypadá to správně.
Tady jsou retries pro jeden job co skončil internal errorem po 4x retries https://papertrailapp.com/groups/23635/events?q=%22Elastic%20server%20error%20response%22%20509529599

![image](https://user-images.githubusercontent.com/903531/58759974-6b813680-8532-11e9-871f-72e4a144914d.png)


![image](https://user-images.githubusercontent.com/903531/58759965-5c9a8400-8532-11e9-9972-7f9f0430b7e2.png)

**Comment by Halama** [comment]
Joby které teď skončily internal errorem:
- 509417361
- 509531639
- 509529599
Každý je ale zalogován 2x s trochu jiným časem a exception-id

Taky to vypadá že pro jiné než tyto joby to retry nedělalo.
![image](https://user-images.githubusercontent.com/903531/58760067-72f50f80-8533-11e9-9432-15578ebc0cfb.png)

V EU prošlo bez problému.

**Comment by odinuv** [comment]
tohle už nijak fixovat nebudeme (doufám).
