### ISSUE TITLE
Sync call time out

### ISSUE THREAD

**Issue by yustme** [keboola/syrup#142]
Request, který padnul na 30s timeoutu:
[GET] [\/queue\/metrics?dateFrom=2019-04-01&dateTo=2019-06-04&period=month]"
https://keboola.slack.com/archives/C02CGK5CL/p1559732415000800

Projekt EU - MALL:
{"id":251,"name":"00 PriceIT"}}

**Comment by odinuv** [comment]
duplicate of https://github.com/keboola/syrup-queue/issues/84
