### ISSUE TITLE
Minimum version of symfony

### ISSUE THREAD

**Issue by ErikZigo** [keboola/syrup#143]
Minimalni verze symfony by mela byt 2.8 ne 2.7

https://github.com/keboola/syrup/blob/802ed996c547f4fbc9643bd6c8d2667b059a3345/composer.json#L31

S 2.7 to nepujde nainstalovat diky konfliktum v balickach

**Comment by odinuv** [comment]
to je divny ne "^2.7" umoznuje instalovat i 2.8

**Comment by tomasfejfar** [comment]
@odinuv ne, je to >=2.7.0 <3.0.0 (https://semver.mwl.be/#!?package=symfony%2Fsymfony&version=%5E2.7&minimum-stability=stable)

**Comment by tomasfejfar** [comment]
Jen teda, pokud nějaký balíček potřebuje sf2.8, tak nestačí `composer update balíček` ale musíš `composer update balíček symfony/symfony` (nebo cokoli dalšího co failne). Ideálně teda nedělat `composer update` bez parametrů, který updatne všechno, ale ten by to fixnul taky.

**Comment by ErikZigo** [comment]
@odinuv
Diky object encryptoru se instaluje i `paragonie/random_compat` ve verzi 2+.
Symfony 2.7 tenhle balik taky vyzadujem Ma ale omezeni na `~1.0`.

Takze Syrup 8+ uz s tim starsim symfony nepouzijes.

**Comment by odinuv** [comment]
aha, jasne!

**Comment by tomasfejfar** [comment]
Ale tohle vyřeší composer interně sám, ne? Jakože - to nesouvisí s tím, jaký constraint je v composer.json.

**Comment by odinuv** [comment]
tf: souvisi to s tim, ze nema smysl mit tady 2.7 kdyz je to stejne nerealna kombinace a cim vyssi verzi tam das, tim min pameti composer sezere. Composer update/install je tady u tech starejch krapu fakt pruser - to sezre 6gb ram ani nevis jak

**Comment by ErikZigo** [comment]
> Ale tohle vyřeší composer interně sám, ne? Jakože - to nesouvisí s tím, jaký constraint je v composer.json.

Jako kdybych vedel ze nad tim budete zase pul dne spekulovat tak bych poslal rovnou PR.

**Comment by odinuv** [comment]
nespekulu, jen me to zajimalo (pochopil jsem to trochu obracene) :)

**Comment by tomasfejfar** [comment]
Tak nejde o špekulace, ale o to, jestli to správně chápu :) Je fajn se něco novýho přiučit.

**Comment by ErikZigo** [comment]
@odinuv ty nespekulujes, ale tomas sel zas nahodou okolo :-)

**Comment by odinuv** [comment]
solved in https://github.com/keboola/syrup/commit/0dfc83d888f4a77ede25284b1557c81ceab64a93
