### ISSUE TITLE
Práce s ES

### ISSUE THREAD

**Issue by Halama** [keboola/syrup#18]
Půjde to udělat i bez toho sleep po instert a update.
Místo search se pro metody `getJob` použije přímo GET API které je realtime. Protože nevím v jakém indexu podle id dokument leží musíme se zeptat všech indexů, na to se dá využít MULTI GET API http://www.elastic.co/guide/en/elasticsearch/reference/1.x/docs-multi-get.html.

Bude potřeba vymyslet jak to releasovat aby se něco nerozbilo, myslím že první by to mělo jít na syrup queue a orchestrator. Současný řešení se sleep funguje takže to úplně nehoří.

**Comment by MiroCillik** [comment]
Prvy krok je hotovy. Dalsi krok bude vyhodenie tych sleepov a takmer urcite aj tych cyklov, kde to kontroluje, po update a create, ze ci uz sa zmena prejavila. To ale mozme spravit az ked vsetky komponenty budu na Syrupe 2.2.10. Takze za az naprsi a uschne :)
