### ISSUE TITLE
Sessions in Symfony 2.6

### ISSUE THREAD

**Issue by ErikZigo** [keboola/syrup#19]
Other session configuration (with BC break) in Symfony 2.6
http://symfony.com/doc/current/cookbook/configuration/pdo_session_storage.html

**Comment by JakubMatejka** [comment]
Jestli na to spěcháš a víš jak to opravit tak doporučuju nečekat a poslat pull request. ;o) Já se k tomu moc brzy nedostanu.

**Comment by ErikZigo** [comment]
Fixed in 2.2.6
