### ISSUE TITLE
app vs component

### ISSUE THREAD

**Issue by MiroCillik** [keboola/syrup#28]
Dat zmysel 'app' a 'component' parametru v konfiguracii. i.e:

    app: docker
    component: r-stuff

Hlavne aby sa tym nic nerozbilo.

**Comment by ondrejhlavacek** [comment]
V jaký konfiguraci? V dockeru se ten parametr `component` zjišťuje až za běhu.

**Comment by MiroCillik** [comment]
To jo, v konfiguraci je len to app. To som tu spis len poznacil aby sme na to nezabudli.

**Comment by Halama** [comment]
zatím s tímhle počkáme ukazuje se že si vystačíme i bez toho

**Comment by Halama** [comment]
zaviram
