### ISSUE TITLE
Validate parameters in UserException

### ISSUE THREAD

**Issue by odinuv** [keboola/syrup#30]
Change signature of UserException::__construct (and SyrupComponentException::__construct) to
public function __construct($message, $previous = null, *array* $data = [])
(or handle non-array data in SyrupComponentException::$this->setData($data); )

Otherwise an error like this is produced which prevents the error from being logged properly
message":"Catchable Fatal Error: Argument 1 passed to Syrup\\ComponentBundle\\Exception\\SyrupComponentException::setData() must be of the type array, object given, called in shiny-bundle\/vendor\/syrup\/component-bundle\/Syrup\/ComponentBundle\/Exception\/SyrupComponentException.php on line 24 and defined in

I think changing the signature should not break anything because it is enforced in the setData method anywa, though it may cause a problem for exceptions derived from UserException?

**Comment by MiroCillik** [comment]
$data musi byt vzdy array. Ak tam chces dat nejaky objekt, tak ho nacpi do pola.. ['objekt' => $objekt].. A ako navrhujes zmenit tu UserException? Vsak ten konstruktor je taky ako pises:

        public function __construct($message, $previous = null, $data = []) { ... }

**Comment by odinuv** [comment]
Je mi jasny, ze je to pole, ale constructor tam nema type hint, kdezto setData() ano, takze kdyz tam z nejakyho duvodu (chyba) neposles pole tak to nezarve v miste vyvolani vyjimky, ale v constructoru vyjimky (cili pri obsluze vyjimky)

**Comment by MiroCillik** [comment]
ahaa uz to vidim
