### ISSUE TITLE
Access token must be set should be UserException

### ISSUE THREAD

**Issue by MiroCillik** [keboola/syrup#31]
Exepcia sa vyhodi pri builde kontajneru, pretoze servisi zavisle na SAPI servisi overuju token vo svojich konstruktoroch :)

https://keboola.slack.com/archives/syrup/p1431342613000017

**Comment by odinuv** [comment]
nevim jestli to s tim souvisi nebo ne, ale taky jsem se dost casto setkal s tim, ze spatnej token byl application exception, nijak jsem se v tom zatim nepitval, takze je to mozna kompletne unrelated

**Comment by MiroCillik** [comment]
ano to je presne ono, pricinu toho som popisal v tom prvom komente.
