### ISSUE TITLE
Run job

### ISSUE THREAD

**Issue by Halama** [keboola/syrup#39]
It is returing only few attributes from job:
![image](https://cloud.githubusercontent.com/assets/903531/9541279/ebf886ae-4d66-11e5-991c-4dd01ac141b8.png)

Can you return whole job? It will allow faster transition to job detail in ui and faster refresh of last runs.
Whole job:
![image](https://cloud.githubusercontent.com/assets/903531/9541296/10326684-4d67-11e5-8d9e-722edf9a418a.png)

**Comment by MiroCillik** [comment]
ok, will do

**Comment by MiroCillik** [comment]
Solved
