### ISSUE TITLE
syrup queue - workers list - improvements

### ISSUE THREAD

**Issue by Halama** [keboola/syrup#43]
This is workers list in SAPI
![image](https://cloud.githubusercontent.com/assets/903531/10042548/18e8731a-61ec-11e5-9dcf-8b8cedbaf53f.png)

Missing in syrup workers list:

* time diff is represented in readable format
* if time from last change is higher than 1 hour item is RED (this is true also for idle workers)
* can we attach also project name to list?

**Comment by MiroCillik** [comment]
Done in 2.4.2
