### ISSUE TITLE
šifrování

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/syrup#44]
Máme s @odin návrh na vylepšení syrupu a šifrování. přibyl by API call, kterým by se zašifroval (pomocí bezpečný knihovny!) nějaký text nebo objekt (podle content-type) a v aplikaci pak bude nějaká metoda/servisa, která bude umět rozšifrovat libovolnej strukturovanej objekt (respektive hodnoty v něm). zašifrovaný hodnoty by byly identifikovaný třeba pomocí `#` v klíči. 

proč a detaily jsou popsaný v  https://keboola.slack.com/archives/docker/p1443047135000126

**Comment by Halama** [comment]
Bude ten `#` prefix v klíči spolehlivý?
Vidím např. že LuckyGuess to používá
![image](https://cloud.githubusercontent.com/assets/903531/10192056/cbfb7514-6779-11e5-8f00-5f2982946a40.png)

Tak ale mohl by to zkusit rozšifrovat a když to nepůjde tak vrátí v původní podobě.

Taky by to mohlo být nějak takhle:

```json
{
  "username": "neco",
  "password": {
     "KBC::Encrypted": "==sifra..."
  }
}

```

A po rozšifrování:
```json
{
  "username": "neco",
  "password": "1234"
}
```

**Comment by ondrejhlavacek** [comment]
Mřížku (můžeme jí vyměnit za jakejkoliv jinej znak nebo znaky) jsem volil proto, že umožňuje jednodušší obousměrný šifrování. Na API pošlu

```
{
  "username": "neco",
  "#password": "1234",
  "#key": "secret"
}
```
a dostanu
```
{
  "username": "neco",
  "#password": "==sifra",
  "#key": "==sifra"
}
```
Ušetří to čas requestům z UI. 

Možná by šlo poslat objekt a s tím i seznam elementů, který chci zašifrovat, potom by to mohlo být přesně jak píšeš.

**Comment by Halama** [comment]
Když bych v tom prvním případě ale např v ui přidal nové atributy které chci zašifrovat a pak to celé poslal na to API tak ty co už byly zašifrované to přešifruje dvakrát ne?

**Comment by ondrejhlavacek** [comment]
Dobrá pointa! By to poznalo, že to je zašifrovaný a znova by to nešifrovalo:

```
{
  "username": "neco",
  "#password": "KBC::Encrypted==sifra",
  "#key": "tohleteprvechcizasifrovat"
}
```

V UI to pak bude hrozně jednoduchý a ani nebudu muset sledovat, jestli se to pole změnilo a mám ho zašifrovat nebo ne. V UI by se navíc musely ty zašifrovaný elementy nějak řešit, by to místo stringu byl najednou objekt.

**Comment by Halama** [comment]
ok

**Comment by ondrejhlavacek** [comment]
Nevypadá to vizuálně nijak pěkně, ale přijde mi, že to bude snadno použitelný. Ten LuckyGuess bude v pohodě, protože v tom atributu s mřížkou je objekt a ne jen string, takže to to bude taky ignorovat.
