### ISSUE TITLE
Šifrování - variabilní klíče

### ISSUE THREAD

**Issue by odinuv** [keboola/syrup#49]
tak to bude tak, že upravíme syrup
- třída CryptoWrapper bude registrovaná servisa (s vlastním namespacem), která bude obsahovat prefix šifry
- třída ObjectEncryptor při dešifrování projede (kontejneroiterace) všechny CryptoWrappery (danýho namespacu) a bude matchovat prefixy na začátek šifry a nalezenýma CryptoWrapper servisama
- syrup si zaregistruje 1 cryptowrapper jako servisu (s generálním klíčem) a registruje mu současnej prefix (`KBC::Encrypted==`)
- docker-bundle si zaregistruje 2 cryptowrappery jako servisy a registruje jim příslušný prefix (`KBC::ComponentEncrypted==`, `KBC::ComponentProjectEncrypted==`) a injectne jim potřebný parametry jak do současnýho JobCryptoWrapperu. (edited)

bude to 100% kompatibilní s obecným šifrováním, šifrám, který byly encodovaný přes komponentu bude stačit změnit prefix z `KBC::Encrypted==` na `KBC::ComponentProjectEncrypted==`, ale je to zatím v jednom martinově testovcím projektu a v integračních testech

**Comment by odinuv** [comment]
+ nedešifrovatelný šifry nesmí vyhazovat výjimku, protože šifry se můžou a) dostat do jiné komponenty b) může si do nich napsat kdo chce co chcce

**Comment by JakubMatejka** [comment]
Nebylo by možný ten ObjectEncryptor rovnou nějak líp pojmenovat?
(Respektive možná všechny ty *Encryptor a Crypto* třídy zkonsolidovat)

**Comment by odinuv** [comment]
Me to pojmenovani prijde celkem logicky: ObjectEncryptor je servisa, ktera zajistuje zasifrovani/rozsifrovani objektu (string, pole) a CryptoWrapper je obal (volanej ObjectEncryptorem) okolo vlastni sifrovaci tridy, ktery zajistuje aby se ji dostaly spravny klice. ObjectEncryptor by mel zustat jeden, CryptoWrapper muze komponenta pridavat dalsi. Encryptor je legacy trida, kterou nebude uplne snadny vyhodit, protoze bysme museli vsechno presifrovat

**Comment by odinuv** [comment]
I kdyz me napada, ze by ted udelat v tom ObjectEncryptoru fallback na tu legacy tridu, aby to umelo rozsifrovat i ty stary sifry (a timpadem by se ji dalo casem zbavit)

**Comment by JakubMatejka** [comment]
To by bylo fajn, nebo by se to dalo aspoň třeba prejmenovat na
LegacyEncryptor. Mně tam vlastně spíš mátlo to že  ObjectEncryptor má někde
v kódu proměnnou $configEncryptor a ještě je to tam pohromadě s tím
původním Encryptorem, tak jsem moc nevěděl co je k čemu

**Comment by MiroCillik** [comment]
Toto je hotove ze? PR som mergol do 2.6. V 3.0 by sa to este mohlo trochu precistit, idealne sa uplne zbavit toho LegacyEncryptoru co?

**Comment by odinuv** [comment]
Zbavit se LegacyEncryptoru by technicky nemel byt problem (bude to zpetne kompatibilni zmena), ale nevim, kdy bude ten spravny okamzik to udelat - jak pozname, ze uz nepotrebujeme rozsifrovat stare sifry?

**Comment by MiroCillik** [comment]
No to je prave ten problem (mi pak doslo). Ja tym napriklad sifrujem access tokeny pre OAuth. Takze by som musel najprv zmigrovat vsechny konfigurace, kde je nieco zasifrovane - rozsifrovat starym klicom a zasifrovat novym. A pak by sa to mohlo vyhodit. Kazdopadne Syrup release 3.x je na to idealny, pretoze pak to bude musiet byt az v 4.x

**Comment by Halama** [comment]
@odinuv je tohle issue ještě aktuální?

**Comment by odinuv** [comment]
https://github.com/orgs/keboola/projects/16
