### ISSUE TITLE
Remove containers from class constructors

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/syrup#53]
These are pretty ugly anti-patterns:
- https://github.com/keboola/syrup/blob/master/src/Keboola/Syrup/Job/ExecutorFactory.php#L19
- https://github.com/keboola/syrup/blob/master/src/Keboola/Syrup/Service/ObjectEncryptor.php#L34

**Comment by odinuv** [comment]
Jo, v tom ObjectEncryptoru to zustalo dokud jsem jeste nevedel jak pouzit DI compiler pass. Uz vim jak to udelat lip, obejde se to bez toho. V tom Exectoru nevim no - mozna by to slo udelat taky pres ten DI compiler pass? Co na to @MiroCillik ?

**Comment by MiroCillik** [comment]
Podla mna to v pripade toho Executoru nie je anti-pattern, Executor mozes vnimat ako controller, vychodzi bod aplikacie, kde chces mat pristup k vsetkym moznym servisam, pricom Executor sam servisa nie je.
Navyse kazdy vo svojej apke (vo svojom exekutore) bude chciet pouzit ine servisy, specificke pre danu apku napriklad. 
Mozno by to slo cez ten compiler pass, akoze by nebol tento abstraktny Executor ale vlozil by sa tam vzdy ten specificky pre danu aplikaciu(?) Pozriem sa na to, mozno by som sa zamyslel aj nad nejakym funkcionalnym pristupom :)

**Comment by MiroCillik** [comment]
V tom ObjectEncryptore ale rozhodne suhlasim, ze to tam nema co robit :)

**Comment by odinuv** [comment]
Prijde mi, ze je to podobny - mohl bys mit v services otagovanou tu servicu, kterou chces pouzit jako jobExecutor pro danou componentu (tj mozna tag = jmeno componenty nebo tak nejak?)

**Comment by MiroCillik** [comment]
Tak nejak by to mohlo byt.

**Comment by JakubMatejka** [comment]
Ok, s tím Exekutorem je to vlastně fakt, nechám teda na vás ;o)

**Comment by MiroCillik** [comment]
Vyriesene v 2.6
