### ISSUE TITLE
Limit pro paralelni beh jobu

### ISSUE THREAD

**Issue by ErikZigo** [keboola/syrup#60]
Podpora: Funguje ve vsech komponentach, ktere bezi na ~~posledni verzi Syrupu~~ vyvojove vetvi syrup/jobs-limit@2eb4db123213ea85911b528643439bb2353e49b5

### Nastaveni limitu

Pomoci SAPI featury projektu: `syrup-jobs-limit-X` *(`X` max pocet paralne bezicich jobu)*
Uprava je zpetne kompatibilni.

### Validace
Limit se overuje na urovni [JobCommandu](https://github.com/keboola/syrup/blob/jobs-limit/src/Keboola/Syrup/Command/JobCommand.php#L146), pri samotnem spusteni komponenty.

Pri validaci se spocita aktualni pocet bezicich jobu (`processing`, `terminating`). Do tohoto souctu nejsou zahrnute komponenty, u kterych je [povoleno neomezene spusteni](https://github.com/keboola/syrup/blob/jobs-limit/src/Keboola/Syrup/Service/StorageApi/Limits.php#L20) *(orchestrator)*.

Validace resi i pripad, kdy muze dojit k `deadlocku`.
**Priklad**: Je spustena `komponenta1`, ktera vola dalsi `komponentu2` a zaroven je dosazeno maximalniho limitu. V tomto pripade se spusti i podrizeny job `komponenty2`. *(Pokud `komponenta1` vola vice podrizenych komponent, spousti se podrizene joby postupne!)*

### Demo
Ukazkova orchestrace *(Parallel limit test)*,  vcetne simulace deadlocku https://connection.keboola.com/admin/projects/288/orchestrations
Nastaveny limit: **3**

**Comment by ErikZigo** [comment]
@Halama Popsal jsem to, snad je to alespon trochu srozumitelne

**Comment by MiroCillik** [comment]
tohle mohlo ist niekam do konfigu nie? https://github.com/keboola/syrup/blob/jobs-limit/src/Keboola/Syrup/Service/StorageApi/Limits.php#L18

**Comment by ErikZigo** [comment]
@MiroCillik Do jakeho configu? Bavili jsme se s @Halama ze to je docasne, nez bude pro to podpora v KBC, pak se ta konfigurace bude nacitat odtamtud.

**Comment by MiroCillik** [comment]
@ErikZigo ok

**Comment by Halama** [comment]
@ErikZigo Zkus prosim nejak vic popsat to spousteni a limitovani podrizenych jobu, moc tomu z popisu ani kodu nerozumim.

**Comment by ErikZigo** [comment]
@Halama Jo pokusim se.

Jinak je to myslim celke jasne videt z ty testovaci orchestrace. Staci ji spustit a pak se kouknout do jobs

**Comment by Halama** [comment]
Teda nerozumim hlavne tomuhle `Pokud komponenta1 vola vice podrizenych komponent, spousti se podrizene joby postupne`

**Comment by Halama** [comment]
Pisu komenty jeste do kodu uz to zacinam a chapat. To posledni omezeni mi prijde mozna zbytecny?

**Comment by ErikZigo** [comment]
Posledni omezeni je pro pripad, ze by podrizenych jobu bylo vic a bezely paralelne (orchestrator).

**Comment by Halama** [comment]
Tam asi udelam do toho ui jobu nejakou vizualizaci timeline aby slo videt jak bezi

**Comment by Halama** [comment]
Tak uz jsme si to tady vysvetlili. je to ok. Puvodne jsem myslel ze by na kazde urovni povolil pustit az `maxLimit` jobu ale to je blbost. Takhle umozni pustit vzdy max jeden novy v dalsi urovani.

**Comment by Halama** [comment]
Tak uz je mozne nastaveni limitu nacitat z nastaveni projektu. Jde o limit `components.jobsParallelism` a vrací ho `verifyToken` metoda http://docs.keboola.apiary.io/#reference/tokens-and-permissions/token-verification/token-verification

Nastavovat ho ruzne projektum je mozne pres manage API https://sites.google.com/a/keboola.com/devel/kbc/sapi/limity-projektua

**Comment by Halama** [comment]
A ten limit bych proste nacetl z te service tady https://github.com/keboola/syrup/blob/2e8da73ca5e2416bf930d5bcba955cec5628ae5e/src/Keboola/Syrup/Command/JobCommand.php#L104 a poznamenal si ho jako promennou isntance

**Comment by MiroCillik** [comment]
Tak ja by som to zrefaktoroval ked budem presuvat tie DB zamky do Syrup Queue OK?

**Comment by MiroCillik** [comment]
Suvisi s https://github.com/keboola/syrup/issues/72
