### ISSUE TITLE
Storage service - log data

### ISSUE THREAD

**Issue by Halama** [keboola/syrup#67]
Dívám se na performance api callů na syrup a všiml jsem si že se tam pořád zbytečně 2x volá verify token.

Poprvé se to zavolá tady https://github.com/keboola/syrup/blob/34cb87ae9cd89064048bc6d56dded1b91c5d4f07/src/Keboola/Syrup/Service/StorageApi/StorageApiService.php#L48

A podruhé díky `getLogData`
https://github.com/keboola/syrup/blob/2f95149711fcdf3dab0b3e9542bdf866cfd1bd2a/src/Keboola/Syrup/Monolog/Processor/SyslogProcessor.php#L33

Nejradši bych to `getLogData` ze sapi klienta uplně vyhodil a pak by se to celé dalo pořešit v téhle service?

**Comment by MiroCillik** [comment]
Vyriesene
