### ISSUE TITLE
Nový job startuje i když ještě běží cleanup předchozího

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/syrup#72]
Šlo by nějak udělat, aby se nový job nastartoval, až když skončí nebo je killnutý cleanup předchozího killnutého jobu? Míchá mí to dost karty při generování credentials na Redshiftu (nový job získá credentials, který za malou chvíli souběžně běžící cleanup smaže).

**Comment by MiroCillik** [comment]
Dalo by sa to spravit tak, ze by sa vytvaranie zamkov presunulo z JobCommandu do ReceiveCommandu vo fronte, takze oba processy run a cleanup by mali rovnaky zamok

**Comment by MiroCillik** [comment]
Fronta si zo SAPI zisti, jestli prislusna komponenta podporuje tuto ficuru (bolo updtatnuta na Syrup 3.1). Ak ano, zamek spravi fronta ak nie, vytvaranie zamkov prenecha fronta komponente (fallback to legacy mode :) ).

**Comment by MiroCillik** [comment]
Zaroven sa zrefaktoroju "Limit pre paralelni beh jobu" a to tak, ze sa tento mechanizmus presunie do Fronty (tam kde sa riesia zamky) a bude fungovat len pre komponenty so Syrupom 3.1. @martin co myslis? Zoznam ficur, ktore komponenta podporuje dostanem zo SAPI ako plz?

**Comment by ondrejhlavacek** [comment]
Takže by se zjišťovalo, jestli je komponenta na syrup 3.1 přes featuru/flag komponenty? Ten se zjistí v seznamu komponent 

![https___connection_keboola_com_v2_storage_](https://cloud.githubusercontent.com/assets/497675/12511674/7c4efdbc-c113-11e5-96b5-d36ae6c997b4.png)

https://github.com/keboola/storage-api-php-client/blob/master/src/Keboola/StorageApi/Client.php#L145

**Comment by Halama** [comment]
jj jeste me napadlo jestli to neudelat obracene, tzn. vsem komponentam dat flag ze to jeste nepodporuji a po upgradu ho naopak odebirat. Tim se to samo procistit.

Mam to tak v tendenci vetsinou i delat v kodu ze to co se chysta byt nahrazeno se uz na zacatku prepne na vedlejsi vetev a pak uz se jenom smazne.

**Comment by MiroCillik** [comment]
jo to je dobry napad!

**Comment by ondrejhlavacek** [comment]
Děje se to furt, dávám reopen

**Comment by ondrejhlavacek** [comment]
https://connection.keboola.com/admin/projects/1218/jobs/228712713?q=
https://connection.keboola.com/admin/projects/1218/jobs/228714427?q=

**Comment by odinuv** [comment]
obsolete
