### ISSUE TITLE
SAPI klient backoff

### ISSUE THREAD

**Issue by Halama** [keboola/syrup#74]
Máme nastavený backoff na cca 45 minut, to se hodí na workerech že to přežije nějakou kratčí maintenance.
Problém je to ale na API serverech tam je to zaseká. Bylo by dobrý teda nějak rozlišit jestli je SAPI klient použitý na workeru nebo na API serveru a podle toho mu nastavit backoff. Na API serveru bych backoff dal třeba na max. 3 pokusy.

Jak to imlemenotvat uplne nevim bud nejak primo v syrupu ze pro pouziti z API to nabidne jineho klienta nebo pomoci konfigurace. Mozna by to mohlo byt nastavene pomoci ENV promenne http://12factor.net/config .

**Comment by Halama** [comment]
taky ještě prozkoumám proč to nesestřelil timelimit php

**Comment by MiroCillik** [comment]
Da sa teraz v SAPI clientovi ten backoff nastavit nejak? napr v konstruktore? Kdyz jo, pak by to mohla riesit ta StorageApiService v Syrupu, napr na zaklade ENV premenne, zisti aky je to server a podla toho nastavi a vrati instanci SAPI clienta.

**Comment by Halama** [comment]
jj je to parametr v options konstruktoru

**Comment by Halama** [comment]
https://github.com/keboola/storage-api-php-client/blob/563b1d313618ad963c347edce1c98467b996f9a1/src/Keboola/StorageApi/Client.php#L81

**Comment by MiroCillik** [comment]
Ale chcelo by to osetrit aj na strane Apachea:
http://stackoverflow.com/questions/3389496/how-do-you-increase-the-max-number-of-concurrent-connections-in-apache
