### ISSUE TITLE
Sanitize UTF-8 job result message when updating Elasticsearch

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/syrup#77]
https://connection.keboola.com/admin/utils/logs?file=2016/01/27/2016-01-27-11-57-18-56a8a28e23670-log

**Comment by ondrejhlavacek** [comment]
Similar to https://github.com/keboola/syrup/commit/f9357fac928a9178c9f9f10fcab715de52e6a769#diff-b8a6428d33662eb11fd65a58ccc16cd9

**Comment by ondrejhlavacek** [comment]
https://connection.keboola.com/admin/utils/logs?file=2016/02/15/2016-02-15-11-02-17-56c1a229ef6ac-exception

**Comment by MiroCillik** [comment]
Solved
