### ISSUE TITLE
Encryption exception handling

### ISSUE THREAD

**Issue by kachnitel** [keboola/syrup#79]
Syrup Encryption wrapper should catch the encryption/decryption exception and translate it to an understandable message. Currently the exception thrown by `defuse/php-encryption` has no message at all.

**Comment by odinuv** [comment]
To se uz dela - tady https://github.com/keboola/syrup/blob/master/src/Keboola/Syrup/Service/ObjectEncryptor.php#L205 a tady https://github.com/keboola/syrup/blob/master/src/Keboola/Syrup/Service/ObjectEncryptor.php#L149 Jak se ti povedlo vytvorit vyjimku bez message?

**Comment by MiroCillik** [comment]
Mozme tohle zavrit?

**Comment by ondrejhlavacek** [comment]
cc @kachnitel
