### ISSUE TITLE
PHP Fatal error:  Cannot use object of type Keboola\StorageApi\Client as array

### ISSUE THREAD

**Issue by ErikZigo** [keboola/syrup#81]
Chyba vyvolana v: https://github.com/keboola/syrup/blob/master/src/Keboola/Syrup/Service/StorageApi/Limits.php#L47

Metoda je volana v: 
https://github.com/keboola/syrup/blob/master/src/Keboola/Syrup/Command/JobCommand.php#L333

**Comment by ErikZigo** [comment]
V syrup 3.0.1

**Comment by Halama** [comment]
to je dost divny, nejakej stack trace?

**Comment by ErikZigo** [comment]
@Halama Zadny neni. Proste mi padaj unit testy orchestratoru. V PT nic nevidim.

@MiroCillik Driv tohle pouzivalo SAPI::getLogData (vracelo array). Ted tam posilas ale reponse token/verify, coz je objekt a ne pole. Hadam ze bude stacit to pretypovat.
Ty ale ted predelavas ty limity ne?

Trochu me udivuje, ze to nehlasi nikdo, kdo bezi na 3.X syrupu.

**Comment by Halama** [comment]
metody sapi klienta vzdy vraceji obyc pole. Hlavne ta hlaska rika ze to tam cpe celeho sapi klienta coz mi prave prijde divny :)

**Comment by MiroCillik** [comment]
to mi pride divne, vsak by to failovalo vsade nie?

**Comment by ErikZigo** [comment]
Posilam tam v testech nesmysl (nebylo to zmineny v upgrade, ze si to mam upravit :-/)

**Comment by ErikZigo** [comment]
Takze je to ok
