### ISSUE TITLE
Invalid token - don't log S3 attachment

### ISSUE THREAD

**Issue by Halama** [keboola/syrup#89]
Log do S3 není potřeba a zpomalí ten API call tím pádem nám pak řve alerting:

![image](https://cloud.githubusercontent.com/assets/903531/17203369/56c11e20-549f-11e6-843c-f6178cedaea2.png)

![image](https://cloud.githubusercontent.com/assets/903531/17203365/4f3aed84-549f-11e6-9913-7e26556d4210.png)

**Comment by odinuv** [comment]
obsolete
